### ISSUE TITLE
arquivos de relações

### ISSUE THREAD

**Issue by arademaker** [own-pt/wn#2]
Só devemos gerar  arquivos `rel-A-B.txt` onde A e B são VerbSynset, AdjectiveSynset, NounSynset e AdverbSynset.

**Comment by fredsonaguiar** [comment]
Manteremos relações CoreConcept, mas removemos seeAlso, InstanceOf, hasInstance, classifiedBy. Eventualmente, faz sentido parametrizarmos os arquivos a serem gerados, e/ou a ser ignorados, assim como tipos.

**Comment by arademaker** [comment]
Core e Base são tipos, não relações.

**Comment by arademaker** [comment]
Acho que não precisamos investir muito mais nisso. Se os lugares no código estiverem claros, qualquer coisa mudamos o código.
