### ISSUE TITLE
pending bugs

### ISSUE THREAD

**Issue by arademaker** [own-pt/wn#3]
1. retirar palavras MWE (palavras com espaço antes de transformar espaço em underscore)

2. menos de 30 linhas nao produz o arquivo

3. (core,# senses) ordenar core com menos senses na frente na lista coluna 2

4. arquivos com coluna direita vazia

5. substanceMeronymOf ??

**Comment by fredsonaguiar** [comment]
1. Estamos remevendo palavras com espaço, e com underscore, como "sistema hidráulico" e "fluxo_de_caixa".
2. As saídas são geradas a partir de uma quantidade mínima de linhas parametrizada.
3. Já corrigido. A ordenação ocorre como deveria.
4. Já corrigido. As saídas só são geradas se as colunas direita e esquerda são preenchidas.
5. Adicionamos essa, assim como outras relações, incluindo relações em portugues.
